# Generated by Django 3.1.3 on 2022-05-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_auto_20220508_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='square',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Descrição'),
        ),
    ]
