# Generated by Django 3.1.3 on 2022-05-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_auto_20220508_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'ordering': ('name',), 'verbose_name': 'Árvore', 'verbose_name_plural': 'Árvores'},
        ),
        migrations.AddField(
            model_name='tree',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome'),
        ),
    ]
