# Generated by Django 3.1.3 on 2022-05-08 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_auto_20220508_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='trees.family'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='is_display',
            field=models.BooleanField(default=True, verbose_name='Exibir'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome popular'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='trees.specie'),
        ),
    ]
