# Generated by Django 3.1.3 on 2022-05-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_auto_20220508_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='source',
            field=models.CharField(choices=[('Nativa', 'nativa'), ('Exótica', 'exotica'), ('Natica e Exótica', 'nativa_exotica')], max_length=20, verbose_name='Origem'),
        ),
    ]
