# Generated by Django 3.1.3 on 2022-05-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0007_auto_20220508_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='source',
            field=models.CharField(choices=[('nativa', 'Nativa'), ('exotica', 'Exótica'), ('nativa_exotica', 'Nativa e Exótica')], max_length=20, verbose_name='Origem'),
        ),
    ]
