# Generated by Django 3.1.3 on 2022-05-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0008_auto_20220508_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
