# Generated by Django 3.1.3 on 2022-05-11 22:47

from django.db import migrations, models
import trees.models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0010_auto_20220508_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='altimg1',
            field=models.CharField(blank=True, max_length=150, verbose_name='Alt imagem 1'),
        ),
        migrations.AddField(
            model_name='square',
            name='altimg2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Alt imagem 2'),
        ),
        migrations.AddField(
            model_name='square',
            name='altimg3',
            field=models.CharField(blank=True, max_length=150, verbose_name='Alt imagem 3'),
        ),
        migrations.AddField(
            model_name='tree',
            name='altimg1',
            field=models.CharField(blank=True, max_length=150, verbose_name='Alt imagem 1'),
        ),
        migrations.AddField(
            model_name='tree',
            name='altimg2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Alt imagem 2'),
        ),
        migrations.AddField(
            model_name='tree',
            name='altimg3',
            field=models.CharField(blank=True, max_length=150, verbose_name='Alt imagem 3'),
        ),
        migrations.AlterField(
            model_name='square',
            name='image1',
            field=models.ImageField(blank=True, upload_to=trees.models.get_file_path, verbose_name='imagem 1'),
        ),
        migrations.AlterField(
            model_name='square',
            name='image2',
            field=models.ImageField(blank=True, upload_to=trees.models.get_file_path, verbose_name='imagem 2'),
        ),
        migrations.AlterField(
            model_name='square',
            name='image3',
            field=models.ImageField(blank=True, upload_to=trees.models.get_file_path, verbose_name='imagem 3'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='image1',
            field=models.ImageField(blank=True, upload_to=trees.models.get_file_path, verbose_name='imagem 1'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='image2',
            field=models.ImageField(blank=True, upload_to=trees.models.get_file_path, verbose_name='imagem 2'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='image3',
            field=models.ImageField(blank=True, upload_to=trees.models.get_file_path, verbose_name='imagem 3'),
        ),
    ]
