# Generated by Django 3.1.3 on 2022-05-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0011_auto_20220511_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
