# Generated by Django 3.1.3 on 2022-05-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0012_auto_20220511_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='is_display',
            field=models.BooleanField(default=True, verbose_name='Exibir'),
        ),
    ]
